nome_digitado = input("digite seu nome")
print("ola,", nome_digitado + "!")
print("como esta seu dia?")
resposta = ("bem")
resposta2 = ("mais o menos")
resposta3 = ("mal")
resposta = print("que bom,", nome_digitado + "!")
resposta2 = print("o que aconteceu,", nome_digitado + "?")